# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GetdbFields(object):
    def setupUi(self, GetdbFields):
        GetdbFields.setObjectName("GetdbFields")
        GetdbFields.setWindowModality(QtCore.Qt.WindowModal)
        GetdbFields.resize(588, 473)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fydfav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GetdbFields.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GetdbFields)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 568, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Database = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Database.sizePolicy().hasHeightForWidth())
        self.label_Database.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Database.setFont(font)
        self.label_Database.setObjectName("label_Database")
        self.horizontalLayout_3.addWidget(self.label_Database)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbProject = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbProject.sizePolicy().hasHeightForWidth())
        self.cbProject.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbProject.setFont(font)
        self.cbProject.setObjectName("cbProject")
        self.horizontalLayout.addWidget(self.cbProject)
        self.pbProject = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbProject.setFont(font)
        self.pbProject.setObjectName("pbProject")
        self.horizontalLayout.addWidget(self.pbProject)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cbDataset = QtWidgets.QComboBox(self.layoutWidget)
        self.cbDataset.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDataset.sizePolicy().hasHeightForWidth())
        self.cbDataset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbDataset.setFont(font)
        self.cbDataset.setObjectName("cbDataset")
        self.horizontalLayout_2.addWidget(self.cbDataset)
        self.pbDataset = QtWidgets.QPushButton(self.layoutWidget)
        self.pbDataset.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbDataset.setFont(font)
        self.pbDataset.setObjectName("pbDataset")
        self.horizontalLayout_2.addWidget(self.pbDataset)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cbSubject = QtWidgets.QComboBox(self.layoutWidget)
        self.cbSubject.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSubject.sizePolicy().hasHeightForWidth())
        self.cbSubject.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbSubject.setFont(font)
        self.cbSubject.setObjectName("cbSubject")
        self.horizontalLayout_6.addWidget(self.cbSubject)
        self.pbSubject = QtWidgets.QPushButton(self.layoutWidget)
        self.pbSubject.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbSubject.setFont(font)
        self.pbSubject.setObjectName("pbSubject")
        self.horizontalLayout_6.addWidget(self.pbSubject)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.cbCondition = QtWidgets.QComboBox(self.layoutWidget)
        self.cbCondition.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCondition.sizePolicy().hasHeightForWidth())
        self.cbCondition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbCondition.setFont(font)
        self.cbCondition.setObjectName("cbCondition")
        self.horizontalLayout_7.addWidget(self.cbCondition)
        self.pbCondition = QtWidgets.QPushButton(self.layoutWidget)
        self.pbCondition.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbCondition.setFont(font)
        self.pbCondition.setObjectName("pbCondition")
        self.horizontalLayout_7.addWidget(self.pbCondition)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.cbSetup = QtWidgets.QComboBox(self.layoutWidget)
        self.cbSetup.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSetup.sizePolicy().hasHeightForWidth())
        self.cbSetup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbSetup.setFont(font)
        self.cbSetup.setObjectName("cbSetup")
        self.horizontalLayout_10.addWidget(self.cbSetup)
        self.pbSetup = QtWidgets.QPushButton(self.layoutWidget)
        self.pbSetup.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbSetup.setFont(font)
        self.pbSetup.setObjectName("pbSetup")
        self.horizontalLayout_10.addWidget(self.pbSetup)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.cbStimulus = QtWidgets.QComboBox(self.layoutWidget)
        self.cbStimulus.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbStimulus.sizePolicy().hasHeightForWidth())
        self.cbStimulus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbStimulus.setFont(font)
        self.cbStimulus.setObjectName("cbStimulus")
        self.horizontalLayout_11.addWidget(self.cbStimulus)
        self.pbStimulus = QtWidgets.QPushButton(self.layoutWidget)
        self.pbStimulus.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbStimulus.setFont(font)
        self.pbStimulus.setObjectName("pbStimulus")
        self.horizontalLayout_11.addWidget(self.pbStimulus)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_Investigator = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Investigator.sizePolicy().hasHeightForWidth())
        self.label_Investigator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Investigator.setFont(font)
        self.label_Investigator.setObjectName("label_Investigator")
        self.horizontalLayout_13.addWidget(self.label_Investigator)
        self.cbInvestigator = QtWidgets.QComboBox(self.layoutWidget)
        self.cbInvestigator.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInvestigator.sizePolicy().hasHeightForWidth())
        self.cbInvestigator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbInvestigator.setFont(font)
        self.cbInvestigator.setObjectName("cbInvestigator")
        self.horizontalLayout_13.addWidget(self.cbInvestigator)
        self.pbInvestigator = QtWidgets.QPushButton(self.layoutWidget)
        self.pbInvestigator.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbInvestigator.setFont(font)
        self.pbInvestigator.setObjectName("pbInvestigator")
        self.horizontalLayout_13.addWidget(self.pbInvestigator)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_ID = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ID.sizePolicy().hasHeightForWidth())
        self.label_ID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.horizontalLayout_5.addWidget(self.label_ID)
        self.ed_ID = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ed_ID.sizePolicy().hasHeightForWidth())
        self.ed_ID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ed_ID.setFont(font)
        self.ed_ID.setObjectName("ed_ID")
        self.horizontalLayout_5.addWidget(self.ed_ID)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.ed_Log = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ed_Log.sizePolicy().hasHeightForWidth())
        self.ed_Log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ed_Log.setFont(font)
        self.ed_Log.setObjectName("ed_Log")
        self.horizontalLayout_9.addWidget(self.ed_Log)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Date = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Date.sizePolicy().hasHeightForWidth())
        self.label_Date.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Date.setFont(font)
        self.label_Date.setObjectName("label_Date")
        self.horizontalLayout_4.addWidget(self.label_Date)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinSessnr = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinSessnr.sizePolicy().hasHeightForWidth())
        self.spinSessnr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinSessnr.setFont(font)
        self.spinSessnr.setObjectName("spinSessnr")
        self.horizontalLayout_4.addWidget(self.spinSessnr)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(9, 1)
        self.verticalLayout.setStretch(10, 1)
        GetdbFields.setCentralWidget(self.centralwidget)

        self.retranslateUi(GetdbFields)
        QtCore.QMetaObject.connectSlotsByName(GetdbFields)

    def retranslateUi(self, GetdbFields):
        _translate = QtCore.QCoreApplication.translate
        GetdbFields.setWindowTitle(_translate("GetdbFields", "Follow Your Data"))
        self.label_Database.setText(_translate("GetdbFields", "Enter fields for database : "))
        self.label.setText(_translate("GetdbFields", "Project"))
        self.pbProject.setText(_translate("GetdbFields", "New"))
        self.label_2.setText(_translate("GetdbFields", "Dataset"))
        self.pbDataset.setText(_translate("GetdbFields", "New"))
        self.label_6.setText(_translate("GetdbFields", "Subject"))
        self.pbSubject.setText(_translate("GetdbFields", "New"))
        self.label_7.setText(_translate("GetdbFields", "Condition"))
        self.pbCondition.setText(_translate("GetdbFields", "New"))
        self.label_10.setText(_translate("GetdbFields", "Setup"))
        self.pbSetup.setText(_translate("GetdbFields", "New"))
        self.label_11.setText(_translate("GetdbFields", "Stimulus"))
        self.pbStimulus.setText(_translate("GetdbFields", "New"))
        self.label_Investigator.setText(_translate("GetdbFields", "Investigator"))
        self.pbInvestigator.setText(_translate("GetdbFields", "New"))
        self.label_ID.setText(_translate("GetdbFields", "Session Id:"))
        self.label_4.setText(_translate("GetdbFields", "logfile"))
        self.label_Date.setText(_translate("GetdbFields", "Date : "))
        self.dateEdit.setDisplayFormat(_translate("GetdbFields", "M-d-yyyy"))
        self.label_3.setText(_translate("GetdbFields", "Session nr."))
        self.btnSave.setText(_translate("GetdbFields", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GetdbFields = QtWidgets.QMainWindow()
    ui = Ui_GetdbFields()
    ui.setupUi(GetdbFields)
    GetdbFields.show()
    sys.exit(app.exec_())
